default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: omer
  password: omer
  host: localhost

development:
  <<: *default
  database: app_templete_my_last_development

test:
  <<: *default
  database: app_templete_my2_last_test
