default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: jisr
  password: jisr
  host: localhost

development:
  <<: *default
  database: app_templete_my_last1_development

test:
  <<: *default
  database: app_templete_my2_last_test
